app/upload/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField
from wtforms import SubmitField
from wtforms.validators import DataRequired
import os

# Upload form class
class UploadForm(FlaskForm):
    file = FileField('Upload Documents',validators=[DataRequired()])
    submit = SubmitField('Upload')

app/upload/routes.py
import os
import shutil
import hashlib
from flask import Blueprint, render_template, flash, redirect, request, url_for
from werkzeug.utils import secure_filename
from app import app, db
from app.upload.forms import UploadForm
from app.models import Document
from app.upload.doc_pdf.embedding import ProcessPDFDocument
from app.upload.doc_text.embedding import ProcessTextDocument
from app.upload.doc_docx.embedding import ProcessDocxDocument
from app.upload.doc_csv.embedding import ProcessCSVDocument
from app.upload.doc_excel.embedding import ProcessExcelDocument


# Create a Blueprint instance for the 'upload' module
upload_route = Blueprint('upload', __name__, template_folder='templates')

# Determine the configuration to use based on an environment variable
config_name = os.getenv('FLASK_CONFIG', 'development')

# File upload path
UPLOAD_FOLDER = os.path.join(app.root_path, 'static', 'documents')
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

# Vector database path
VECTOR_DB_PATH = os.path.join(app.root_path, 'static', 'vectordb')
os.makedirs(VECTOR_DB_PATH, exist_ok=True)

# Allowed Extentions
# The supported file types are PDF, MD, TXT, DOCX, HTML, CSV, XLS, and XLSX.
ALLOWED_EXTENSIONS = {'pdf', 'txt', 'docx', 'csv', 'xls', 'xlsx'}
ALLOWED_EXTENSIONS_STR = ", ".join(ALLOWED_EXTENSIONS)
app.config['MAX_CONTENT_LENGTH'] = 200 * 1024 * 1024
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

# Allowed file types
def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

# Get the file size
def get_pdf_file_size(file_path) -> str:
    # Get the file size in bytes
    size_bytes = os.path.getsize(file_path)
    # Determine the appropriate unit (KB or MB) based on file size
    if size_bytes < 1024:
        file_size = f'{size_bytes} bytes'
    elif size_bytes < 1024 * 1024:
        file_size = f'{size_bytes / 1024:.2f} KB'
    else:
        file_size = f'{size_bytes / (1024 * 1024):.2f} MB'

    return file_size

# Identify the document type
def identify_document_type(file_path) -> str:
    # Use the file extension to identify the document type
    file_extension = os.path.splitext(file_path)[1][1:].lower()
    if file_extension == 'pdf':
        return 'PDF'
    elif file_extension in ['md', 'txt' ]:
        return 'Text'
    elif file_extension == 'docx':
        return 'Docx' 
    elif file_extension in ['csv']:
        return 'CSV'
    elif file_extension in ['xlsx', 'xls']:
        return 'EXCEL'
    else:
        return 'Unknown'
    
# Add a route for the upload page
@upload_route.route('/upload', methods=['GET', 'POST'])
def upload():
    # Pagination
    page = request.args.get('page', 1, type=int)
    # Total documents uploaded
    total_documents = Document.query.count()
    # Documents per page
    documents_per_page = 5
    # Get the documents for the current page
    documents = Document.query.order_by(Document.id.desc()).paginate(page=page, per_page=documents_per_page, error_out=False)

    form = UploadForm()
    if form.validate_on_submit():
        # Get the uploaded file from the form
        file = request.files['file']
        file_name = secure_filename(file.filename)
        file_path = os.path.join(app.config['UPLOAD_FOLDER'], file_name)
        
        if file and allowed_file(file_name):
            # Check if the md5sum of the file is already available in the database
            md5sum = hashlib.md5(file.read()).hexdigest()
            file.seek(0)
            document = Document.query.filter_by(md5sum=md5sum).first()
            if document:
                flash(f"Document already exists! '{file_name}'", 'danger')
                return redirect(request.url)
            # Save the file to the upload folder
            file.save(file_path)

            # Identify the document type
            document_type = identify_document_type(file_path)
            # Case for document type
            match document_type:
                case 'PDF':
                    # Process the PDF document
                    process_pdf = ProcessPDFDocument(file_path, VECTOR_DB_PATH)
                    if not process_pdf.embed_doc():
                        flash(f"Failed to process PDF document! '{file_name}'", 'danger')
                        return redirect(request.url)
                case 'Text':
                    # Process the text document
                    process_text = ProcessTextDocument(file_path, VECTOR_DB_PATH)
                    if not process_text.embed_doc():
                        flash(f"Failed to process text document! '{file_name}'", 'danger')
                        return redirect(request.url)
                case 'Docx':
                    process_docx = ProcessDocxDocument(file_path, VECTOR_DB_PATH)
                    if not process_docx.embed_doc():
                        flash(f"Failed to process docx document! '{file_name}'", 'danger')
                        return redirect(request.url)
                case 'CSV':
                    process_csv = ProcessCSVDocument(file_path, VECTOR_DB_PATH)
                    if not process_csv.embed_doc():
                        flash(f"Failed to process EXCEL document! '{file_name}'", 'danger')
                        return redirect(request.url)
                case 'EXCEL':
                    process_excel = ProcessExcelDocument(file_path, VECTOR_DB_PATH)
                    if not process_excel.embed_doc():
                        flash(f"Failed to process EXCEL document! '{file_name}'", 'danger')
                        return redirect(request.url)
                    
            # Get the document size
            document_size = get_pdf_file_size(file_path)
           
            # Create a new Document instance and add it to the database
            document = Document(name=file_name, size=document_size, path=file_path, md5sum=md5sum)
            db.session.add(document)
            db.session.commit()

            # Redirect to the home page after successful upload
            flash(f"Document uploaded successfully! '{file_name}'", 'success')
            return redirect(url_for('upload.upload'))
        else:
            flash(f"Document type not allowed! '{file_name}'", 'danger')
            return redirect(request.url)
    return render_template('upload/upload.html', title='Upload', form=form, documents=documents, total_documents=total_documents)

# Clear Database
@upload_route.route('/clear_database', methods=['GET', 'POST'])
def clear_database():
    # Remove the vector database folder
    shutil.rmtree(VECTOR_DB_PATH, ignore_errors=True)
    # Create the vector database folder
    os.makedirs(VECTOR_DB_PATH, exist_ok=True)
    # Clear the documents folder
    shutil.rmtree(UPLOAD_FOLDER, ignore_errors=True)
    # Create the documents folder
    os.makedirs(UPLOAD_FOLDER, exist_ok=True)
    # Clear the documents from the database
    Document.query.delete()
    db.session.commit()
    flash('Database cleared successfully!', 'success')
    return redirect(url_for('upload.upload'))

app/upload/templates/upload/layout.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{title}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='css/cover.css')}}">

</head>

<body class="bg-dark">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <header class="mb-auto">
            <div>
                <h3 class="float-md-start mb-0" style="color: chocolate;">ragify.ai</h3>
                <nav class="nav nav-masthead justify-content-center float-md-end">
                    {% if title == 'Home' %}
                        <a class="nav-link fw-bold py-1 px-0 active" href="{{url_for('home.index')}}">Home</a>
                    {% else %}
                        <a class="nav-link fw-bold py-1 px-0" href="{{url_for('home.index')}}">Home</a>
                    {% endif %}
                    {% if title == 'Upload' %}
                        <a class="nav-link fw-bold py-1 px-0 active" aria-current="page" href="{{url_for('upload.upload')}}">Add Document</a>
                    {% else %}
                        <a class="nav-link fw-bold py-1 px-0" aria-current="page" href="{{url_for('upload.upload')}}">Add Document</a>
                    {% endif %}
                    {% if title == 'Query' %}
                        <a class="nav-link fw-bold py-1 px-0 active" href="{{url_for('query.query')}}">Query Your Document</a>
                    {% else %}
                        <a class="nav-link fw-bold py-1 px-0" href="{{url_for('query.query')}}">Query Your Document</a>
                    {% endif %}
                    
                </nav>
            </div>
        </header>
    </div>
    <main>
        <div class="container-lg mt-5">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category,message in messages %}
            <div class="alert alert-{{category}} alert-dismissible fade show mt-2" role="alert">
                <strong>{{message}}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
            {% block content %} {% endblock %}
        </div>
        <footer class="footer mt-auto py-3 bg-dark text-white text-center">
            <div class="container">
                <p class="mb-0">&copy; 2024 Ragify.ai. All rights reserved.</p>
                <p class="mb-0">Developed by Prashant Pokhriyal</p>
            </div>
        </footer>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

app/upload/templates/upload/upload.html
{% extends 'upload/layout.html'%}
{% block content %}
<div class="row">
    <div class="col py-5 border-end">
        <form action="" method="POST" enctype="multipart/form-data" id="uploadForm">
            {{form.hidden_tag()}}
            <div class="mb-3">
                {{form.file(class="form-control w-80 mb-2")}}
                <small class="text-muted text-white">
                    Supported document formats: PDF, TXT, DOCX, XLS, XLSX, CSV. You can upload up to 200MB
                    file size.
                </small>
            </div>
            <div class="mb-3">
                {{form.submit(class="btn btn-sm btn-success me-3", id="submitButton")}}
                <div class="spinner-border spinner-border-sm text-warning d-none" id="spinner" role="status">
                    <span class="visually-hidden">Loading...</span>
                </div>
            </div>
        </form>
    </div>
    {% if total_documents == 0 %}
        <div class="col py-5">
            <div class="alert alert-warning d-flex align-items-center" role="alert">
                <i class="bi bi-info-circle me-2"></i>
                <div>No documents found.</div>
            </div>
        </div>
    {% else %}
        <div class="col py-2">
            <div class="d-grid gap-2 d-md-flex justify-content-md-end mb-2">
                <a class="btn btn-primary btn-sm me-md-1" href="{{url_for('upload.clear_database')}}" role="button">Clear Database</a>
            </div>
            <table class="table table-sm table-bordered table-hover">
                <thead class="table-secondary">
                    <tr>
                        <th scope="col">Uploaded Document</th>
                        <th scope="col">Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for doc in documents.items %}
                        <tr>
                            <td>{{doc.name}}</td>
                            <td>Embedded</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}
    </div>
</div>
{% block script %}
<script>
    const form = document.getElementById('uploadForm');
    const spinner = document.getElementById('spinner');
    const submitButton = document.getElementById('submitButton');

    form.addEventListener('submit', () => {
        spinner.classList.remove('d-none');
        submitButton.disabled = true; // Disable the submit button
    });
</script>
{% endblock script %}
{% endblock content %}